### PR TITLE
Feature/use host bounds

### PR DESCRIPTION
**Pull request by megheaiulian**
Adds useHostBounds hook.

### CODE REVIEW

**Comment by nomego** [comment]
Does this replicate the top/right/bottom/left 0 + position absolute css approach?
But I assume it's used in different scenarios?

**Comment by megheaiulian** [comment]
@nomego This just get's you a updated (resize observer) bounds/contentRect (top/right/width/height) for your host element.

**Comment by nomego** [comment]
Ah so the child might not replicate the sizing, the use case would be something like dialogs and dropdowns making sure they fit in the parent?

**Comment by megheaiulian** [comment]
I am using it in autocomplete https://github.com/Neovici/cosmoz-autocomplete/pull/65 as you described it (a dropdown/dialog for suggestions with position fixed) .

**Pull request merged**
