### PR TITLE
fix: replacing momentum with time-elements

### PR DESCRIPTION
**Pull request by dotpointer**
Replacing momentum with time-elements for the `timeago` function.

To run tests, do `npm run test -- --skip-plugin sauce`.

Not how to solve the `unknown revision or path not in the working tree` error in the tests.

Issue is RM:21039.

### CODE REVIEW

**Comment by JockeCK** [comment]
@dotpointer The reason the build fails is because of an lint commit error. 
To fix this you need  in this file: .github/workflows/workflow.yml 

change:
 uses: actions/checkout@master
to:
uses: actions/checkout@v1


See this commit for more details and reasoning:
https://github.com/Neovici/cosmoz-treenode-navigator/pull/67/commits/bb372efd7301c19f0e3332faba2d0d21ec898436

**Comment by dotpointer** [comment]
@JockeCK Your suggestions fixed the problem.

Now there is an error related to the money part which I have not changed:
> expected 'US$2,200,200.33' to equal '$2,200,200.33'

**Comment by JockeCK** [comment]
> @JockeCK Your suggestions fixed the problem.
> 
> Now there is an error related to the money part which I have not changed: `expected 'US$2,200,200.33' to equal '$2,200,200.33'`.
Yes, for some reason, there is an difference between firefox and chrome. Only the firefox test fails.

**Comment by JockeCK** [comment]
Fun stuff, tried the tests manually & locally on firefox version 72. worked fine

**Comment by dotpointer** [comment]
> Fun stuff, tried the tests manually & locally on firefox version 72. worked fine

I suspect the not related money error may have to do with the locale used.

**Comment by dotpointer** [comment]
Closing in favor of #44.

**Pull request closed without merging**
